name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo add-apt-repository -y ppa:ubuntugis/ppa
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
          python -m pip install requests numpy
          python -m pip install pyproj shapely==1.8.* matplotlib
          python -m pip install GDAL==$(gdal-config --version)
          python -m pip install pandas geopandas
          python -m pip install flake8 pytest
          sudo add-apt-repository -y --remove ppa:ubuntugis/ppa
          sudo apt-get update
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=15 --max-line-length=127 --statistics
      - name: Test with unittest
        run: |
          export PYTHONPATH=
          export PYTHONPATH=$PYTHONPATH:geodataflow/api/
          export PYTHONPATH=$PYTHONPATH:geodataflow/core/
          export PYTHONPATH=$PYTHONPATH:geodataflow/spatial/
          export PYTHONPATH=$PYTHONPATH:geodataflow/dataframes/
          export PYTHONPATH=$PYTHONPATH:geodataflow/spark/
          export PYTHONPATH=$PYTHONPATH:geodataflow/sql/
          python -m unittest geodataflow/core/tests/test_*.py
          python -m unittest geodataflow/spatial/tests/test_*.py
          python -m unittest geodataflow/dataframes/tests/test_*.py
